name: Node.js CD

on:
  push:
    branches: ["new-master"]
  pull_request:
    branches: ["new-master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Deploy using SSH Client
        uses: appleboy/ssh-action@new-master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/api-selfservice
            git pull origin new-master
            git status
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 restart api-selfservice
